odometry_publisher:
  ros__parameters:
    # オドメトリ計算に必要な物理パラメータ
    wheel_radius: 0.04
    wheel_base: 0.38
    count_per_rev: 4096.0

parameter_publisher:
  ros__parameters:
    # ESP32に渡すためのパラメータ
    wheel_radius: 0.04
    wheel_base: 0.38
    rkp : 172.5
    rki : 87.0
    rkd : 18.5
    lkp : 172.5
    lki : 87.0
    lkd : 18.5
